# TODO: There is probably a way to simplify this very explicit build matrix.
git:
  depth: 1
  submodules: false
jobs:
  include:
    # We test only building using SPM with Swift 4.2 on macos since Carthage doesn't support multiple Swift language versions.
    - stage: test
      language: swift
      os: osx
      osx_image: xcode10.1 # Swift 4.2
      script:
      - swift --version
      - swift build
      - swift build -c release
    - stage: test
      language: swift
      os: osx
      osx_image: xcode10.3 # Swift 5.0
      env:
      - HOMEBREW_NO_INSTALL_CLEANUP=1
      before_install:
      - brew update
      install:
      - ./utils.py ci install-macos
      before_script:
      - ./utils.py prepare-workspace macos
      script:
      - ./utils.py ci script-macos
    - stage: test
      language: swift
      os: osx
      osx_image: xcode11.3 # Swift 5.1
      env:
      - HOMEBREW_NO_INSTALL_CLEANUP=1
      before_install:
      - brew update
      install:
      - ./utils.py ci install-macos
      before_script:
      - ./utils.py prepare-workspace macos
      script:
      - ./utils.py ci script-macos
    - stage: test
      language: swift
      os: osx
      osx_image: xcode11.4 # Swift 5.2
      env:
      - HOMEBREW_NO_INSTALL_CLEANUP=1
      before_install:
      - brew update
      install:
      - ./utils.py ci install-macos
      before_script:
      - ./utils.py prepare-workspace macos
      script:
      - ./utils.py ci script-macos
    - stage: test
      # TODO: Remove this stage when the non-xcf installation method with Carthage is no longer supported.
      language: swift
      os: osx
      osx_image: xcode12 # Swift 5.3
      env:
      - HOMEBREW_NO_INSTALL_CLEANUP=1
      before_install:
      - brew update
      install:
      - ./utils.py ci install-macos
      before_script:
      - xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
      - trap 'rm -f "$xcconfig"' INT TERM HUP EXIT
      - echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
      - echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig
      - export XCODE_XCCONFIG_FILE="$xcconfig"
      - carthage bootstrap
      - git submodule update --init --recursive
      - cp "Tests/Test Files/gitattributes-copy" "Tests/Test Files/.gitattributes"
      - cd "Tests/Test Files/"
      - git lfs pull
      - git lfs checkout
      - cd -
      script:
      - ./utils.py ci script-macos --new-watchos-simulator
    - stage: test
      language: swift
      os: osx
      osx_image: xcode12.4 # Swift 5.3.2
      env:
      - HOMEBREW_NO_INSTALL_CLEANUP=1
      before_install:
      - brew update
      install:
      - ./utils.py ci install-macos
      before_script:
      - ./utils.py prepare-workspace macos --xcf
      script:
      - ./utils.py ci script-macos --new-watchos-simulator
    - stage: test
      language: generic
      os: linux
      dist: xenial
      env:
      - SWIFT_VERSION=4.2.3
      install:
      - ./utils.py ci install-linux
      script:
      - ./utils.py ci script-linux
    - stage: test
      language: generic
      os: linux
      dist: xenial
      env:
      - SWIFT_VERSION=5.0.3
      install:
      - ./utils.py ci install-linux
      script:
      - ./utils.py ci script-linux
    - stage: test
      language: generic
      os: linux
      dist: xenial
      env:
      - SWIFT_VERSION=5.1.5
      install:
      - ./utils.py ci install-linux
      script:
      - ./utils.py ci script-linux
    - stage: test
      language: generic
      os: linux
      dist: xenial
      env:
      - SWIFT_VERSION=5.2.5
      install:
      - ./utils.py ci install-linux
      script:
      - ./utils.py ci script-linux
    - stage: test
      language: generic
      os: linux
      dist: xenial
      env:
      - SWIFT_VERSION=5.3.3
      install:
      - ./utils.py ci install-linux
      script:
      - ./utils.py ci script-linux
    - stage: deploy
      # Don't deploy if it is a test release.
      if: (tag IS present) AND (tag =~ /^\d+\.\d+\.\d+$/)
      language: generic
      os: osx
      osx_image: xcode12
      env:
      - HOMEBREW_NO_INSTALL_CLEANUP=1
      env:
        secure: iavIkrus2Xd3b086nz2srMGl52yqzLuCdhyEAhMODVqkzqMQ17s10y1TNb+vkepd0HgxI9j57d5X7tfChjWuWDwE2hZKjr/Kx2DfiUr1AKQD6ymuGrq/0Vv6yL9dfPU8goFArcrsBcyVKczLtTuLCKL498ZqokkQc/3kGvzW74lv+z410MfHS9/tvToO/yXJckL6qJ2XBAiElfOO0rEkllTeCo6N3bjcHZ2o7PE0K+CHYxwNKj0TmPmuNWZ3U4fzoWzkk01re1C1l5cpSb20g+2aGyi0yYX+PomX7fIIqNq9vmmyoeNdr35yqoQv/0zFeFnps83NKmZLAjSUhiUdhlbuBLBE+w8544LOaZnMDlFmpDjgyaVnRrOh0NrBB1FwU48aGfX5ljRQmk/07FTEUjvwvGGoOpz8lrLZi148FMHEospL3Sf7d8K+Q9WdtLTGk7HCnbOVcxS6oB/SWF/Cj6n5wu+EI1floBaZEsNPR40Gd4eM/Ik/E3lDrZThGDCWQsao981wm7IfEDBR1nuMME8gpZINFANNS1+5miFaGdTnDTp4Yd5MGEFZm+K8x+TG1891NwNH1ZmKXlypJXiUzvSjbh2ViNJGekdQj9q2gj2ZFlCfHJ05adwJ4w9qRuF00HpAOD6At6EnsjDXFJeTZS5dj8fi2YsU9or8KfTFoNY=
      addons:
        homebrew:
          packages:
          - sourcekitten
          update: true
      install:
      - gem install -N jazzy
      - gem update -N cocoapods
      before_deploy:
      - ./utils.py ci before-deploy
      deploy:
      - provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: docs
        skip_cleanup: true
        on:
          tags: true
