trigger:
  branches:
    exclude:
    - master
  tags:
    include:
    - '*'

stages:
- stage: test
  displayName: 'Build & Test'
  jobs:
  - job: macosLegacy
    strategy:
      matrix:
        macosSwift50:
          imageName: 'macOS-10.14'
          DEVELOPER_DIR: '/Applications/Xcode_10.3.app'
        macosSwift51:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_11.3.1.app'
        macosSwift52:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_11.4.1.app'
    pool:
      vmImage: $(imageName)
    steps:
    - script: |
        brew update
        ./utils.py ci install-macos
      displayName: 'Install'
    - script: ./utils.py prepare-workspace macos
      displayName: 'Prepare Workspace'
    - script: ./utils.py ci script-macos
      displayName: 'Build & Test'
    - script: swift build -c release
      displayName: 'Build SPM Release'
  - job: macosNew
    # We split Xcode 12+ jobs into a separate matrix since we need to use XCFramework for this versions.
    # We also need to use a different watchos simulator name for newer Xcode versions.
    # For it is only for Swift 5.3 but future versions will also probably be included here.
    strategy:
      matrix:
        macosSwift53:
          imageName: 'macOS-10.15'
          DEVELOPER_DIR: '/Applications/Xcode_12.4.app'
    pool:
      vmImage: $(imageName)
    steps:
    - script: |
        brew update
        ./utils.py ci install-macos
      displayName: 'Install'
    - script: ./utils.py prepare-workspace macos --xcf
      displayName: 'Prepare Workspace'
    - script: ./utils.py ci script-macos --new-watchos-simulator
      displayName: 'Build & Test'
    - script: swift build -c release # Check Release build just in case.
      displayName: 'Build SPM Release'
  - job: linux
    strategy:
      matrix:
        linuxSwift50:
          imageName: 'ubuntu-18.04'
          SWIFT_VERSION: '5.0.3'
        linuxSwift51:
          imageName: 'ubuntu-18.04'
          SWIFT_VERSION: '5.1.5'
        linuxSwift52:
          imageName: 'ubuntu-18.04'
          SWIFT_VERSION: '5.2.5'
        linuxSwift53:
          imageName: 'ubuntu-20.04'
          SWIFT_VERSION: '5.3.3'
    pool:
      vmImage: $(imageName)
    steps:
    - script: ./utils.py ci install-linux
      displayName: 'Install'
    - script: ./utils.py ci script-linux
      displayName: 'Build SPM Debug & Release'
# - stage: Deploy
#   dependsOn: Test
#   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags') # Deploy on tags only
